In [1]:
import numpy as np

In [2]:
X=np.array([[2,3],
            [3,5],
            [4,2],
            [5,6],
            [6,5]])

In [3]:
# Find center using mean
X_centered=X-np.mean(X,axis=0)
X_centered

array([[-2. , -1.2],
       [-1. ,  0.8],
       [ 0. , -2.2],
       [ 1. ,  1.8],
       [ 2. ,  0.8]])

In [4]:
# Convariance Matrix
cov_matrix=np.cov(X_centered,rowvar=False)
print(cov_matrix)

[[2.5  1.25]
 [1.25 2.7 ]]


In [5]:
# Eigen Values and Eigen Vectors
eigenvalues,eigenvectors=np.linalg.eig(cov_matrix)

In [6]:
# Sort Descending and Find Principal Components using Eigenvectors
idx=np.argsort(eigenvalues)[::-1]
eigenvalues=eigenvalues[idx]
eigenvectors=eigenvectors[:,idx]
print("Eigenvalues:\n",eigenvalues)
print("\nEigenvectors(Principal Components)\n",eigenvectors)

Eigenvalues:
 [3.85399362 1.34600638]

Eigenvectors(Principal Components)
 [[-0.6783269  -0.73476024]
 [-0.73476024  0.6783269 ]]


In [7]:
# Find Explained Variance Ratio using Eigenvalues
explained_variance_ratio=eigenvalues/np.sum(eigenvalues)
print(explained_variance_ratio)

[0.74115262 0.25884738]
